Models/User/ChangePasswordModel.cs
using RSecurityBackend.Models.Auth.ViewModels;

namespace GanjooRazor.Models.User
{
    /// <summary>
    /// change password model
    /// </summary>
    public class ChangePasswordModel : SetPasswordModel
    {
        /// <summary>
        /// new password model
        /// </summary>
        public string NewPasswordRepeat { get; set; }
    }
}

Areas/Admin/Pages/ModifyPage.cshtml.cs
using GanjooRazor.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RMuseum.Models.Ganjoor;
using RMuseum.Models.Ganjoor.ViewModels;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace GanjooRazor.Areas.Admin.Pages
{
    public class ModifyPageModel : PageModel
    {
        /// <summary>
        /// HttpClient instance
        /// </summary>
        private readonly HttpClient _httpClient;

        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="httpClient"></param>
        public ModifyPageModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        /// <summary>
        /// Corresponding Ganojoor Page
        /// </summary>
        /// <summary>
        /// api model
        /// </summary>
        [BindProperty]
        public GanjoorModifyPageViewModel ModifyModel { get; set; }

        /// <summary>
        /// rythm
        /// </summary>
        public GanjoorMetre[] Rhythms { get; set; }

        /// <summary>
        /// last message
        /// </summary>
        public string LastMessage { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            LastMessage = Request.Query["edit"] == "true" ? "ویرایش انجام شد." : "";
            if (string.IsNullOrEmpty(Request.Query["id"]))
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "شناسهٔ صفحه مشخص نیست.");
            }
            var rhythmResponse = await _httpClient.GetAsync($"{APIRoot.Url}/api/ganjoor/rhythms");

            rhythmResponse.EnsureSuccessStatusCode();

            Rhythms = JsonConvert.DeserializeObject<GanjoorMetre[]>(await rhythmResponse.Content.ReadAsStringAsync());


            var pageUrlResponse = await _httpClient.GetAsync($"{APIRoot.Url}/api/ganjoor/pageurl?id={Request.Query["id"]}");

            if (!pageUrlResponse.IsSuccessStatusCode)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, await pageUrlResponse.Content.ReadAsStringAsync());
            }

            pageUrlResponse.EnsureSuccessStatusCode();

            var pageUrl = JsonConvert.DeserializeObject<string>(await pageUrlResponse.Content.ReadAsStringAsync());

            var pageQuery = await _httpClient.GetAsync($"{APIRoot.Url}/api/ganjoor/page?url={pageUrl}");
            if (!pageQuery.IsSuccessStatusCode)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, await pageQuery.Content.ReadAsStringAsync());
            }
            GanjoorPageCompleteViewModel page = JObject.Parse(await pageQuery.Content.ReadAsStringAsync()).ToObject<GanjoorPageCompleteViewModel>();

            ModifyModel = new GanjoorModifyPageViewModel()
            {
                Title = page.Title,
                UrlSlug = page.UrlSlug,
                HtmlText = page.HtmlText,
                Note = "",
                SourceName = page.Poem == null ? null : page.Poem.SourceName,
                SourceUrlSlug = page.Poem == null ? null : page.Poem.SourceUrlSlug,
                OldTag = page.Poem == null ? null : page.Poem.OldTag,
                OldTagPageUrl = page.Poem == null ? null : page.Poem.OldTagPageUrl,
                RhymeLetters = page.Poem == null ? null : page.Poem.RhymeLetters,
                Rhythm = page.Poem == null ? null : page.Poem.GanjoorMetre == null ? null : page.Poem.GanjoorMetre.Rhythm
            };

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            using (HttpClient secureClient = new HttpClient())
            {
                if (await GanjoorSessionChecker.PrepareClient(secureClient, Request, Response))
                {
                    var putResponse = await secureClient.PutAsync($"{APIRoot.Url}/api/ganjoor/page/{Request.Query["id"]}", new StringContent(JsonConvert.SerializeObject(ModifyModel), Encoding.UTF8, "application/json"));
                    if (!putResponse.IsSuccessStatusCode)
                    {
                        LastMessage = await putResponse.Content.ReadAsStringAsync();
                    }
                    else
                    {
                        return Redirect($"/Admin/ModifyPage?id={Request.Query["id"]}&edit=true");
                    }
                }
                else
                {
                    LastMessage = "لطفا از گنجور خارج و مجددا به آن وارد شوید.";
                }

            }


            return Page();

        }
    }
}

Areas/User/Pages/AddSong.cshtml.cs
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GanjooRazor.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using RMuseum.Models.Ganjoor.ViewModels;

namespace GanjooRazor.Areas.User.Pages
{
    public class AddSongModel : PageModel
    {
        /// <summary>
        /// Last Error
        /// </summary>
        public string LastError { get; set; }

        /// <summary>
        /// api model
        /// </summary>
        [BindProperty]
        public PoemMusicTrackViewModel PoemMusicTrackViewModel { get; set; }

        /// <summary>
        /// poem id
        /// </summary>
        public int PoemId { get; set; }

        public void OnGet()
        {
            PoemMusicTrackViewModel = new PoemMusicTrackViewModel()
            {
                TrackType = RMuseum.Models.Ganjoor.PoemMusicTrackType.BeepTunesOrKhosousi,
                PoemId = 0,
                ArtistName = "محمدرضا شجریان",
                ArtistUrl = "http://beeptunes.com/artist/3403349",
                AlbumName = "اجراهای خصوصی",
                AlbumUrl = "http://khosousi.com",
                TrackName = "",
                TrackUrl = "",
                Approved = false,
                Rejected = false,
                BrokenLink = false,
                Description = ""
            };
        }

        public async Task<IActionResult> OnPostAsync()
        {
            using (HttpClient secureClient = new HttpClient())
            {
                if (await GanjoorSessionChecker.PrepareClient(secureClient, Request, Response))
                {
                    var putResponse = await secureClient.PostAsync($"{APIRoot.Url}/api/ganjoor/song/add", new StringContent(JsonConvert.SerializeObject(PoemMusicTrackViewModel), Encoding.UTF8, "application/json"));
                    if (!putResponse.IsSuccessStatusCode)
                    {
                        LastError = await putResponse.Content.ReadAsStringAsync();
                    }
                }
                else
                {
                    LastError = "لطفا از گنجور خارج و مجددا به آن وارد شوید.";
                }

            }


            if (!string.IsNullOrEmpty(LastError))
            {
                return Page();
            }

            return Redirect("/User/AddSong");
        }
    }
}

Areas/User/Pages/Index.cshtml.cs
using GanjooRazor.Models.User;
using GanjooRazor.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using RSecurityBackend.Models.Auth.ViewModels;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace GanjooRazor.Areas.Panel.Pages
{
    public class IndexModel : PageModel
    {
        /// <summary>
        /// api model
        /// </summary>

        [BindProperty]
        public RegisterRAppUser UserInfo { get; set; }

        [BindProperty]
        public ChangePasswordModel ChangePasswordModel { get; set; }

        /// <summary>
        /// Last Error
        /// </summary>
        public string LastError { get; set; }

        /// <summary>
        /// password changed
        /// </summary>
        public string PasswordChanged { get; set; }

        /// <summary>
        /// get
        /// </summary>
        public async Task OnGetAsync()
        {
            LastError = "";
            PasswordChanged = "";
            await _PreparePage();
        }

        private async Task _PreparePage()
        {
            using (HttpClient secureClient = new HttpClient())
            {
                if (await GanjoorSessionChecker.PrepareClient(secureClient, Request, Response))
                {
                    var userInfoResponse = await secureClient.GetAsync($"{APIRoot.Url}/api/users/{Request.Cookies["UserId"]}");
                    if (userInfoResponse.IsSuccessStatusCode)
                    {
                        PublicRAppUser userInfo = JsonConvert.DeserializeObject<PublicRAppUser>(await userInfoResponse.Content.ReadAsStringAsync());

                        UserInfo = new RegisterRAppUser()
                        {
                            Id = userInfo.Id,
                            Username = userInfo.Username,
                            FirstName = userInfo.FirstName,
                            SureName = userInfo.SureName,
                            NickName = userInfo.NickName,
                            PhoneNumber = userInfo.PhoneNumber,
                            Email = userInfo.Email,
                            Website = userInfo.Website,
                            Bio = userInfo.Bio,
                            RImageId = userInfo.RImageId,
                            Status = userInfo.Status,
                            IsAdmin = false,
                            Password = ""
                        };
                    }
                    else
                    {
                        LastError = await userInfoResponse.Content.ReadAsStringAsync();
                    }
                }
                else
                {
                    LastError = "لطفا از گنجور خارج و مجددا به آن وارد شوید.";
                }
            }
        }

        public async Task<IActionResult> OnPostSetMyInfoAsync(RegisterRAppUser UserInfo)
        {
            LastError = "";
            PasswordChanged = "";
            using (HttpClient secureClient = new HttpClient())
            {
                if (await GanjoorSessionChecker.PrepareClient(secureClient, Request, Response))
                {
                    var isAdminResponse = await secureClient.GetAsync($"{APIRoot.Url}/api/users/isadmin?userId={Request.Cookies["UserId"]}");
                    if (isAdminResponse.IsSuccessStatusCode)
                    {
                        UserInfo.IsAdmin = JsonConvert.DeserializeObject<bool>(await isAdminResponse.Content.ReadAsStringAsync());

                        var putResponse = await secureClient.PutAsync($"{APIRoot.Url}/api/users/{Request.Cookies["UserId"]}", new StringContent(JsonConvert.SerializeObject(UserInfo), Encoding.UTF8, "application/json"));

                        if(!putResponse.IsSuccessStatusCode)
                        {
                            LastError = await putResponse.Content.ReadAsStringAsync();
                        }
                    }
                    else
                    {
                        LastError = await isAdminResponse.Content.ReadAsStringAsync();
                    }
                }
                else
                {
                    LastError = "لطفا از گنجور خارج و مجددا به آن وارد شوید.";
                }
            }
            await _PreparePage();
            return Page();
        }

        public async Task<IActionResult> OnPostSetMyPassAsync(ChangePasswordModel ChangePasswordModel)
        {
            LastError = "";
            PasswordChanged = "";
            if (ChangePasswordModel.NewPasswordRepeat != ChangePasswordModel.NewPassword)
            {
                LastError = "گذرواژهٔ جدید با تکرار آن همسان نیست.";
                return Page();
            }
            if(ChangePasswordModel.NewPassword == ChangePasswordModel.OldPassword)
            {
                LastError = "گذرواژهٔ جدید با گذرواژهٔ کنونی یکسان است.";
                return Page();
            }
            using (HttpClient secureClient = new HttpClient())
            {
                if (await GanjoorSessionChecker.PrepareClient(secureClient, Request, Response))
                {
                    var changePassResp = await secureClient.PostAsync($"{APIRoot.Url}/api/users/setmypassword", 
                        new StringContent(JsonConvert.SerializeObject
                            (
                            new SetPasswordModel()
                            {
                                OldPassword = ChangePasswordModel.OldPassword,
                                NewPassword = ChangePasswordModel.NewPassword
                            }
                            ), 
                        Encoding.UTF8, "application/json"));
                    if (!changePassResp.IsSuccessStatusCode)
                    {
                        LastError = await changePassResp.Content.ReadAsStringAsync();
                    }
                    else
                    {
                        PasswordChanged = "گذرواژهٔ شما به درستی تغییر کرد.";
                    }
                }
                else
                {
                    LastError = "لطفا از گنجور خارج و مجددا به آن وارد شوید.";
                }
            }
            await _PreparePage();
            return Page();
        }
    }
}

Areas/User/Pages/AddSong.cshtml
@page
@model GanjooRazor.Areas.User.Pages.AddSongModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
    ViewData["Title"] = "آهنگ مرتبط از منابع دلخواه";
    await GanjooRazor.Utils.GanjoorSessionChecker.ApplyPermissionsToViewData(Request, Response, ViewData);
}

<h1>@ViewData["Title"]</h1>

@if (Model.LastError != "")
{
    <h2>@Model.LastError</h2>
}


<form method="post">
    <table style="width:100%" class="noborder">
        <tr>
            <td>
                <span class="inputlabel">شناسهٔ شعر: </span>
            </td>
            <td>
                <input asp-for="PoemMusicTrackViewModel.PoemId" />
            </td>
        </tr>

        <tr>
            <td>
                <span class="inputlabel">خواننده: </span>
            </td>
            <td>
                <input style="width:100%" asp-for="PoemMusicTrackViewModel.ArtistName" /><br />
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">نشانی خواننده:</span>
            </td>
            <td>
                <input style="width:100%;text-align:left;direction:ltr;" asp-for="PoemMusicTrackViewModel.ArtistUrl" />
            </td>
        </tr>
        <tr>
            <td>
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">آلبوم:</span>
            </td>
            <td>
                <input style="width:100%" asp-for="PoemMusicTrackViewModel.AlbumName" /><br />
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">نشانی آلبوم:</span>
            </td>
            <td>
                <input style="width:100%;text-align:left;direction:ltr;" asp-for="PoemMusicTrackViewModel.AlbumUrl" />
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">آهنگ:</span>
            </td>
            <td>
                <input style="width:100%" asp-for="PoemMusicTrackViewModel.TrackName" />
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">نشانی آهنگ:</span>
            </td>
            <td>
                <input style="width:100%;text-align:left;direction:ltr;" asp-for="PoemMusicTrackViewModel.TrackUrl" />
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">توضیح: </span>
            </td>
            <td>
                <input style="width:100%" asp-for="PoemMusicTrackViewModel.Description" /><br />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit" name="approve" id="approve" style="width:100%;color:white;background-color:green">تأیید</button>
            </td>

        </tr>

    </table>

</form>

Areas/User/Pages/Index.cshtml
@page
@model GanjooRazor.Areas.Panel.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
    ViewData["Title"] = "پیشخان کاربر";
    await GanjooRazor.Utils.GanjoorSessionChecker.ApplyPermissionsToViewData(Request, Response, ViewData);
}
<h1>@ViewData["Title"]</h1>
@if (Model.LastError != "")
{
    <h2>@Model.LastError</h2>
}
else
{
    <form method="post" asp-page-handler="SetMyPass">
        <table style="width:100%" class="noborder">
            <tr>
                <td colspan="2">
                    <h2>تغییر گذرواژه</h2>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="inputlabel">گذرواژهٔ کنونی: </span>
                </td>
                <td>
                    <input type="password" style="width:100%" asp-for="ChangePasswordModel.OldPassword" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    <span class="inputlabel">گذرواژهٔ جدید: </span>
                </td>
                <td>
                    <input type="password" style="width:100%" asp-for="ChangePasswordModel.NewPassword" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    <span class="inputlabel">تکرار گذرواژهٔ جدید: </span>
                </td>
                <td>
                    <input type="password" style="width:100%" asp-for="ChangePasswordModel.NewPasswordRepeat" /><br />
                </td>
            </tr>
            
            <tr>
                <td>
                    @Model.PasswordChanged
                </td>
                <td>
                    <button type="submit" name="approve" id="approve" style="width:100%;color:white;background-color:green">تغییر گذرواژه</button>
                </td>
            </tr>

        </table>
    </form>
    <form method="post" asp-page-handler="SetMyInfo">
        <table style="width:100%" class="noborder">
            <tr>
                <td colspan="2">
                    <h2>تغییر مشخصات</h2>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="inputlabel">نام: </span>
                </td>
                <td>
                    <input style="width:100%" asp-for="UserInfo.FirstName" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    <span class="inputlabel">نام خانوادگی: </span>
                </td>
                <td>
                    <input style="width:100%" asp-for="UserInfo.SureName" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    <span class="inputlabel">نام مستعار (نمایش در حاشیه‌ها): </span>
                </td>
                <td>
                    <input style="width:100%" asp-for="UserInfo.NickName" /><br />
                </td>
            </tr>
            <tr>
                <td>
                    <span class="inputlabel"><a target="_blank" href="@Html.Raw(Model.UserInfo.Website)">وبگاه:</a></span>
                </td>
                <td>
                    <input style="width:100%;text-align:left;direction:ltr;" asp-for="UserInfo.Website" />
                </td>
            </tr>
            <tr>
                <td>
                    <span class="inputlabel">دربارهٔ من: </span>
                </td>
                <td>
                    <textarea asp-for="UserInfo.Bio" class="editor"></textarea>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="hidden" asp-for="UserInfo.Id" />
                    <input type="hidden" asp-for="UserInfo.Email" />
                    <input type="hidden" asp-for="UserInfo.Username" />
                    <input type="hidden" asp-for="UserInfo.Password" />
                    <input type="hidden" asp-for="UserInfo.PhoneNumber" />
                    <input type="hidden" asp-for="UserInfo.Status" />
                    <input type="hidden" asp-for="UserInfo.RImageId" />
                </td>
                <td>
                    <button type="submit" name="approve" id="approve" style="width:100%;color:white;background-color:green">ذخیره</button>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <a href="/hashieha/?userid=@Model.UserInfo.Id" target="_blank">نمایهٔ عمومی من</a>
                </td>
            </tr>

        </table>
    </form>
}

Areas/User/Pages/ModifyPage.cshtml
@page
@model GanjooRazor.Areas.User.Pages.ModifyPageModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
    ViewData["Title"] = "ویرایش";
}

<h1>@ViewData["Title"]</h1>

<p>@Model.LastMessage</p>

<form method="post">
    <table style="width:100%" class="noborder">
        <tr>
            <td>
                <span class="inputlabel">شناسهٔ صفحه: </span>
            </td>
            <td>
                <span class="inputlabel"><a href="/?p=@Request.Query["id"]">@Request.Query["id"]</a></span>
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">عنوان: </span>
            </td>
            <td>
                <input asp-for="ModifyModel.Title" />
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">نامک: </span>
            </td>
            <td>
                <input style="text-align:left;direction:ltr;" asp-for="ModifyModel.UrlSlug" />
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">متن: </span>
            </td>
            <td>
                <textarea asp-for="ModifyModel.HtmlText" tabindex="4" rows="20" cols="80"></textarea>
            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">منبع (شعر): </span>
            </td>
            <td>
                <table>
                    <tr>
                        <td><span>نام:</span> <input asp-for="ModifyModel.SourceName" /></td>
                    </tr>
                    <tr>
                        <td><span>نشانی:</span> <input style="text-align:left;direction:ltr;" asp-for="ModifyModel.SourceUrlSlug" /></td>
                    </tr>
                </table>

            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">دسته‌بندی کهن (شعر): </span>
            </td>
            <td>
                <table>
                    <tr>
                        <td><span>نام:</span> <input asp-for="ModifyModel.OldTag" /></td>
                    </tr>
                    <tr>
                        <td><span>نشانی:</span> <input style="text-align:left;direction:ltr;" asp-for="ModifyModel.OldTagPageUrl" /></td>
                    </tr>
                </table>

            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">وزن (شعر): </span>
            </td>
            <td>
                <input asp-for="ModifyModel.Rhythm" list="rythms" />
                <datalist id="rythms">
                    @foreach(var rythm in Model.Rhythms)
                    {
                    <option value="@rythm.Rhythm">@rythm.Rhythm</option>
                    }
                </datalist>

            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">حروف قافیه (شعر): </span>
            </td>
            <td>
                <input asp-for="ModifyModel.RhymeLetters" />

            </td>
        </tr>
        <tr>
            <td>
                <span class="inputlabel">توضیح این ویرایش: </span>
            </td>
            <td>
                <input asp-for="ModifyModel.Note" />

            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit" name="approve" id="approve" style="width:100%;color:white;background-color:green">ذخیره</button>
            </td>
        </tr>
    </table>
</form>

Areas/User/Pages/MyComments.cshtml
@page
@model GanjooRazor.Areas.User.Pages.MyCommentsModel
@using DNTPersianUtils.Core
@{
    Layout = "_Layout";
    ViewData["Title"] = "حاشیه‌های من";
    await GanjooRazor.Utils.GanjoorSessionChecker.ApplyPermissionsToViewData(Request, Response, ViewData);
    string color = "gray";
}
<h1>@ViewData["Title"]</h1>
@if (Model.LastError != "")
{
    <h2>@Model.LastError</h2>
}
else
{
    <p style="text-align:center">
        @foreach (var paginationLink in Model.PaginationLinks)
        {
            if (!string.IsNullOrEmpty(paginationLink.Url))
            {
                <a href="@paginationLink.Url">@paginationLink.Name</a>
            }
            else
            {
                @paginationLink.Name
            }
        }
    </p>

    @foreach (var comment in Model.Comments)
    {
        if (color == "gray")
            color = "white";
        else
            color = "gray";

        <div style="background-color:@color" id="comment-@comment.Id">
            <blockquote>
                <div id="comment-text-@comment.Id">
                    @Html.Raw(comment.HtmlComment)
                </div>
                <p>
                    @comment.AuthorName <small>در @comment.CommentDate.ToFriendlyPersianDateTextify()</small> دربارهٔ <a href="@comment.Poem.UrlSlug">@comment.Poem.Title</a>
                </p>
            </blockquote>
            <p>
                <a role="button" onclick="deleteMyComment(@comment.Id)" class="actionlink" title="حذف حاشیه">🗑</a>
                <a role="button" onclick="editMyComment(@comment.Id)" class="actionlink" title="ویرایش حاشیه">✎</a>
            </p>
        </div>


        <hr />
    }

    <p style="text-align:center">
        @foreach (var paginationLink in Model.PaginationLinks)
        {
            if (!string.IsNullOrEmpty(paginationLink.Url))
            {
                <a href="@paginationLink.Url">@paginationLink.Name</a>
            }
            else
            {
                @paginationLink.Name
            }
        }
    </p>

    <div id="id02" class="modal">
        <span onclick="document.getElementById('id02').style.display='none'"
              class="close" title="بستن">&times;</span>
        <form class="modal-content animate" method="post" id="editcommentform" action="?handler=EditComment">
            <table style="max-width:100%; width:100%; margin:0">
                <tr>
                    <td>
                        <textarea name="editCommentText" id="editCommentText" class="inputTextarea editor" tabindex="4" rows="10" style="width:100%"></textarea>
                        <input type="hidden" name="editCommentId" id="editCommentId" value="" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <button name="editcomment" id="editcomment" class="inputSubmit" onclick="return editComment();" style="width:100%">ویرایش حاشیه</button>
                    </td>
                </tr>
            </table>

        </form>
    </div>
}

Areas/User/Pages/Notifications.cshtml
@page
@model GanjooRazor.Areas.User.Pages.NotificationsModel
@using DNTPersianUtils.Core
@{
    Layout = "_Layout";
    ViewData["Title"] = "اعلان‌های من";
    await GanjooRazor.Utils.GanjoorSessionChecker.ApplyPermissionsToViewData(Request, Response, ViewData);
    string color = "gray";
}
<h1>@ViewData["Title"]</h1>
@if (Model.LastError != "")
{
    <h2>@Model.LastError</h2>
}
else
{
    <p style="text-align:center">
        @foreach (var paginationLink in Model.PaginationLinks)
        {
            if (!string.IsNullOrEmpty(paginationLink.Url))
            {
                <a href="@paginationLink.Url">@paginationLink.Name</a>
            }
            else
            {
                @paginationLink.Name
            }
        }
    </p>

    @foreach (var notification in Model.Notifications)
    {
        if (color == "gray")
            color = "white";
        else
            color = "gray";

        <div style="background-color:@color" id="notification-@notification.Id">
            <blockquote>
                <p>
                    @notification.Subject <small>در @notification.DateTime.ToFriendlyPersianDateTextify()</small>
                </p>
                <div id="notification-text-@notification.Id">
                    @Html.Raw(notification.HtmlText)
                </div>
            </blockquote>
            <p>
                <a role="button" onclick="deleteNotification('@notification.Id')" class="actionlink" title="حذف">🗑</a>
            </p>
        </div>


        <hr />
    }

    <p style="text-align:center">
        @foreach (var paginationLink in Model.PaginationLinks)
        {
            if (!string.IsNullOrEmpty(paginationLink.Url))
            {
                <a href="@paginationLink.Url">@paginationLink.Name</a>
            }
            else
            {
                @paginationLink.Name
            }
        }
    </p>

    
}